name: DeployCoverage

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:  |
        mkdir coverage
        echo "<h1>Deploying coverage report</h1>"  > coverage/index.html
      - uses: actions/upload-artifact@v4
        with:
          path: coverage
      - uses: actions/deploy-pages@v2