name: DeployCoverage

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:  mkdir coverage && echo "<h1>Deploying coverage report</h1>"  > coverage/index.html
      - uses: actions/upload-artifact@v4
        with:
          path: coverage/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment

  